#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb echo "Cloning Toolchain, and 
AnyKernel"
git clone --depth=1 https://github.com/Haseo97/Avalon-Clang-11.0.1 -b 11.0.1 clang
git clone --depth=1 https://github.com/Risti699/AnyKernel3 -b master AnyKernel
echo "Done" token=$(openssl enc -base64 -d <<< ODg0MTY1Mzg5OkFBRmxFT0xKUW9LQU53eFVYYnpjUkZvdEkwSHUtY0M4aWlN)
chat_id="-1001469144202"
codename_device=Onclite
PATH=$(pwd)/clang/bin:$PATH
curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>JFLA Kernel</b> New build is UP"'!'"%0A<b>Started on :</b> <code>CircleCI</code>%0A<b>For device :</b> <b>Onclite</b> (Redmi 7 AOSP)%0A<b>Kernel Version :</b> <code>$(make kernelversion)</code>%0A<b>Branch :</b> <code>$(git rev-parse --abbrev-ref HEAD)</code>%0A<b>Under commit :</b> <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0A<b>Compiler :</b> <code>$($(pwd)/clang/bin/clang --version | head -n 1)</code>%0A<b>Started on :</b> <code>$(TZ=Asia/Jakarta date)</code>%0A" tanggal=$(TZ=Asia/Jakarta date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=Kaguyaasama
export KBUILD_BUILD_HOST=CircleCI
# Push kernel to channel
function push() {
	ZIP=$(echo JFLA-Kernel*.zip)
	curl -F document=@$ZIP "https://api.telegram.org/bot$token/sendDocument" \
			-F chat_id="$chat_id" \
			-F "disable_web_page_preview=true" \
			-F "parse_mode=html" \
			-F caption="Build took $(($DIFF / 60)) minute(s) and 
$(($DIFF % 60)) second(s)."
}
function paste() {
    curl -F document=build.log "https://api.telegram.org/bot$token/sendDocument" \
			-F chat_id="$chat_id" \
			-F "disable_web_page_preview=true" \
			-F "parse_mode=html"
}
# Stiker
function stiker() {
	curl -s -F chat_id=$chat_id -F 
sticker="CAACAgIAAx0CV5FcigACB-lfN7YYoshb0mWwKLpKkLK_QfDyXQACGhIAAowt_Qf5VOfIcVrdhRoE" 
https://api.telegram.org/bot$token/sendSticker
	}
# Stiker Error
function stikerr() {
	curl -s -F chat_id=$chat_id -F 
sticker="CAACAgIAAx0CV5FcigACB-RfN7WlNm-bnX4c2g0O6Ha2oq6_2QACDRIAAowt_QfdwLnjK43pQBoE" 
https://api.telegram.org/bot$token/sendSticker
	}
# Fin Error
function finerr() {
        paste
        curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" \
			-d chat_id="$chat_id" \
			-d "disable_web_page_preview=true" \
			-d "parse_mode=markdown" \
			-d text="Build throw an error(s)"
}
make ARCH=arm64 O=out onc_defconfig && \ make -j$(nproc) O=out \
                ARCH=arm64 \
                CC=clang \
                CLANG_TRIPLE=aarch64-linux-gnu- \
                CROSS_COMPILE=aarch64-linux-gnu- \
                CROSS_COMPILE_ARM32=arm-linux-gnueabi- 2>&1| tee kernel.log 
kernel_ver=$(cat $(pwd)/out/.config | grep Linux/arm64 | cut -d " " -f3) if ! [ -a 
$IMAGE ]; then
	finerr
	stikerr
	exit 1 fi cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage paste cd 
AnyKernel zip JFLA-Kernel-$codename_device-${tanggal}.zip * END=$(date +"%s") 
DIFF=$(($END - $START)) push
stiker
